import { getSessionPayload } from '../../../../lib/auth';
import { getSql } from '../../../../lib/db';
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  HeadingLevel,
  AlignmentType,
  WidthType,
} from 'docx';

export const dynamic = 'force-dynamic';
export const maxDuration = 60;

const ENGINE_URL = process.env.NEXT_PUBLIC_ENGINE_URL || 'https://smc-engine.ali-6b8.workers.dev';

function sanitiseFilename(str) {
  return str.replace(/[^a-zA-Z0-9 \-_]/g, '').replace(/\s+/g, ' ').trim().slice(0, 60);
}

function buildDocx(minutes) {
  const {
    title,
    date,
    participants = [],
    executiveSummary = '',
    keyPoints = [],
    decisions = [],
    actionItems = [],
    emptyState = false,
  } = minutes;

  const children = [];

  // Title block
  children.push(
    new Paragraph({
      text: `Minutes: ${title || 'Untitled Meeting'}`,
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: 'Date: ', bold: true }),
        new TextRun(date || 'Unknown'),
      ],
      spacing: { after: 80 },
    }),
  );

  if (participants.length > 0) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: 'Participants: ', bold: true }),
          new TextRun(participants.join(', ')),
        ],
        spacing: { after: 200 },
      }),
    );
  }

  if (emptyState) {
    children.push(
      new Paragraph({
        text: 'No transcript was recorded for this session.',
        spacing: { after: 200 },
      }),
    );
  } else {
    // Executive Summary
    children.push(
      new Paragraph({
        text: 'Executive Summary',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 240, after: 80 },
      }),
      new Paragraph({
        text: executiveSummary || 'No summary available.',
        spacing: { after: 200 },
      }),
    );

    // Key Discussion Points
    children.push(
      new Paragraph({
        text: 'Key Discussion Points',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 240, after: 80 },
      }),
    );
    if (keyPoints.length > 0) {
      for (const point of keyPoints) {
        children.push(new Paragraph({ text: String(point), bullet: { level: 0 } }));
      }
    } else {
      children.push(new Paragraph({ text: 'None recorded.', spacing: { after: 100 } }));
    }

    // Decisions
    children.push(
      new Paragraph({
        text: 'Decisions Made',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 240, after: 80 },
      }),
    );
    if (decisions.length > 0) {
      for (const d of decisions) {
        children.push(new Paragraph({ text: String(d), bullet: { level: 0 } }));
      }
    } else {
      children.push(new Paragraph({ text: 'No decisions recorded.', spacing: { after: 100 } }));
    }

    // Action Items
    children.push(
      new Paragraph({
        text: 'Action Items',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 240, after: 80 },
      }),
    );

    if (actionItems.length > 0) {
      const headerRow = new TableRow({
        children: ['Owner', 'Action', 'Due'].map(text =>
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text, bold: true })] })],
          }),
        ),
      });
      const dataRows = actionItems.map(item =>
        new TableRow({
          children: [
            new TableCell({ children: [new Paragraph(String(item.owner || ''))] }),
            new TableCell({ children: [new Paragraph(String(item.action || ''))] }),
            new TableCell({ children: [new Paragraph(String(item.due || ''))] }),
          ],
        }),
      );
      children.push(
        new Table({
          rows: [headerRow, ...dataRows],
          width: { size: 100, type: WidthType.PERCENTAGE },
        }),
      );
    } else {
      children.push(new Paragraph({ text: 'No action items recorded.', spacing: { after: 100 } }));
    }
  }

  // Footer note
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by Silent Meeting Copilot — ${new Date().toLocaleString('en-GB')}`,
          size: 18,
          color: '888888',
        }),
      ],
      spacing: { before: 400 },
    }),
  );

  return new Document({
    sections: [{ properties: {}, children }],
  });
}

// GET /api/meetings/[id]/minutes-docx
// Downloads a .docx file containing professional meeting minutes.
export async function GET(request, { params }) {
  const session = await getSessionPayload();
  if (!session) return Response.json({ error: 'Unauthorized' }, { status: 401 });

  const { id } = await params;
  const sql = getSql();

  const [meeting] = await sql`
    SELECT id, title, objective, language_mode, context_notes, started_at
    FROM meetings
    WHERE id = ${id} AND user_email = ${session.email}
  `;
  if (!meeting) return Response.json({ error: 'Not found' }, { status: 404 });

  const segments = await sql`
    SELECT speaker, corrected_text, cleaned
    FROM transcript_segments
    WHERE meeting_id = ${id}
    ORDER BY ts
  `;

  const me = segments.filter(s => s.speaker === 'me').map(s => s.cleaned);
  const others = segments
    .filter(s => s.speaker === 'others')
    .map(s => s.corrected_text || s.cleaned);

  const date = new Date(meeting.started_at).toISOString().slice(0, 10);
  const titleSafe = sanitiseFilename(meeting.title || 'Untitled session');
  const filename = `Minutes - ${titleSafe} - ${date}.docx`;

  let minutes;
  if (me.length + others.length < 2) {
    minutes = {
      emptyState: true,
      title: meeting.title || 'Untitled session',
      date,
      participants: [],
      executiveSummary: 'No transcript was recorded for this session.',
      keyPoints: [],
      decisions: [],
      actionItems: [],
    };
  } else {
    try {
      const res = await fetch(`${ENGINE_URL}/minutes`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${process.env.INTERNAL_SHARED_SECRET || ''}` },
        body: JSON.stringify({
          me,
          others,
          title: meeting.title || 'Untitled session',
          date,
          objective: meeting.objective || '',
          contextNotes: meeting.context_notes || '',
        }),
      });
      if (!res.ok) throw new Error(`Engine ${res.status}`);
      const data = await res.json();
      minutes = { ...data, title: meeting.title || 'Untitled session', date };
    } catch (err) {
      return Response.json({ error: String(err) }, { status: 500 });
    }
  }

  const doc = buildDocx(minutes);
  const buffer = await Packer.toBuffer(doc);

  return new Response(buffer, {
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Cache-Control': 'no-store',
    },
  });
}
